# Site Settings
title: Start Jekyll
email: swapnabulbule@gmail.com
description: >
 A guide to getting started with Jekyll.
baseurl: ''
url: 'https://swapnabulbule.github.io'
#twitter_username: taniarascia
github_username: swapnabulbule

# Build Settings
sass:
 sass_dir: _sass
include: ['_pages']
kramdown:
 input: GFM
